automerge:
  image: registry.gitlab.com/gitlab-org/cli:latest
  stage: automerge
  script:
    # Sprawdź, czy MR ma label automerge
    - |
      if [[ "$CI_MERGE_REQUEST_LABELS" == *"automerge"* ]]; then
        echo "Automerge label found, merging MR..."
        glab mr merge "$CI_MERGE_REQUEST_IID" --yes
      else
        echo "No automerge label, skipping."
      fi
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /automerge/'
      when: always